[package]
name = "rs-kepler"
version = "0.1.0"
authors = ["Sebastian Zdanowicz <14982968+szdanowi@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

